# Generated by Django 4.0.6 on 2024-05-18 10:14

import compressor.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('upload', models.FileField(upload_to='uploads/', validators=[compressor.validators.FileValidator.validate_file_extension, compressor.validators.FileValidator.validate_file_size])),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnail/')),
                ('preview', models.FileField(blank=True, null=True, upload_to='previews/')),
                ('original_size', models.FloatField(blank=True, default=float)),
                ('new_size', models.FloatField(blank=True, default=float)),
                ('compression_status', models.CharField(choices=[('PENDING', 'PENDING'), ('CONVERTING', 'CONVERTING'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=25)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('mimetype', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
